name: tree_view
description: A Flutter package for a fully customisable base tree view. Using this package you can build nested tree view with the possibility of making each child widget a parent.
version: 0.0.5
author: Ajil Oommen <ajilo297@gmail.com>
homepage: https://github.com/ajilo297/flutter_tree_view

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
